name: parksync_application
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  http: ^1.3.0
  provider: ^6.1.2
  path_provider: ^2.1.5
  path: ^1.9.0
  shared_preferences: ^2.5.1
  font_awesome_flutter: ^10.8.0
  mobile_scanner: ^6.0.6
  auto_size_text: ^3.0.0
  flutter_vector_icons: ^2.0.0
  sqflite: ^2.4.1
  image_picker: ^1.1.2
  logging: ^1.3.0
  intl: 
  photo_view: ^0.15.0
  cached_network_image: ^3.4.1
  back_button_interceptor: ^8.0.3
  url_launcher: ^6.3.1
  audioplayers: ^6.1.1
  socket_io_client: ^3.0.2
  flutter_local_notifications: ^18.0.1
  easy_localization: 
  flutter_localization: ^0.3.1
  logger: ^2.5.0
  workmanager: ^0.5.2
  flutter_conditional_rendering: ^2.1.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  iconsax: ^0.0.8
  dotted_border: ^2.1.0
  # bluetooth_manager: 
  widgets_to_image: ^1.0.0
  bluetooth_print_plus: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/s.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/cars/
    - assets/countries_data/
    - assets/countries_data/countries/
    - assets/countries_data/flags/
    - assets/sounds/
    - assets/registered_car/
    - assets/translations/



  fonts:
    - family: Kdam
      fonts:
        - asset: assets/fonts/kdam.ttf

